### ISSUE TITLE
[Postman Support]: Exception occurs with duplicate API header keys

### ISSUE THREAD

**Issue by networkinss** [virtualansoftware/idaithalam#121]
Idaithalam throws an error if the API request (like defined in a Postman collection) has duplicate API header keys.
Duplicate or more API header keys are valid REST API requests.
The exception are thrown in Cucumblan.

`
Scenario: Get the test result links for the last test session.. - GET api call # target/testreports/1/feature/virtualan-contract.0.feature:5
Okt 24, 2021 8:46:24 AM io.virtualan.cucumblan.core.BaseStepDefinition before
INFORMATION: scenario ID:: file:///media/amrit/f62417df-6c96-4797-a3d9-a06fb4352655/workspace/api/apitesting/idaithalam/modules/idaithalam/target/testreports/1/feature/virtualan-contract.0.feature:5
  Given a user perform a api action                                            # io.virtualan.cucumblan.core.BaseStepDefinition.readRequestByPathParam(java.lang.String)
  And add request with given header params                                     # io.virtualan.cucumblan.core.BaseStepDefinition.readAllHeaderParams(java.lang.String,java.util.Map<java.lang.String, java.lang.String>)
      io.cucumber.core.exception.CucumberException: Could not convert arguments for step [add (.*) with given header params$] defined at 'io.virtualan.cucumblan.core.BaseStepDefinition.readAllHeaderParams(java.lang.String,java.util.Map<java.lang.String, java.lang.String>)'.
	at io.cucumber.core.runner.PickleStepDefinitionMatch.couldNotConvertArguments(PickleStepDefinitionMatch.java:112)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:56)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:92)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:64)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:104)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:73)
	at io.cucumber.core.runtime.Runtime.lambda$execute$5(Runtime.java:110)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:117)
	at io.cucumber.core.runtime.Runtime.lambda$execute$6(Runtime.java:110)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:233)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at io.cucumber.core.runtime.Runtime.lambda$run$2(Runtime.java:86)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:87)
	at io.cucumber.core.cli.Main.run(Main.java:92)
	at io.virtualan.idaithalam.contract.IdaithalamExecutor.validateContract(IdaithalamExecutor.java:120)
	at io.virtualan.idaithalam.core.api.ParallelExecutor.call(ParallelExecutor.java:49)
	at io.virtualan.idaithalam.core.api.ParallelExecutor.call(ParallelExecutor.java:15)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.cucumber.datatable.CucumberDataTableException: Can't convert DataTable to Map<java.lang.String, java.lang.String>.
Encountered duplicate key X-API-TEST1 with values test1 and test2
	at io.cucumber.datatable.CucumberDataTableException.cantConvertToMap(CucumberDataTableException.java:28)
	at io.cucumber.datatable.CucumberDataTableException.duplicateKeyException(CucumberDataTableException.java:33)
	at io.cucumber.datatable.DataTableTypeRegistryTableConverter.createMap(DataTableTypeRegistryTableConverter.java:299)
	at io.cucumber.datatable.DataTableTypeRegistryTableConverter.toMap(DataTableTypeRegistryTableConverter.java:287)
	at io.cucumber.datatable.DataTableTypeRegistryTableConverter.convert(DataTableTypeRegistryTableConverter.java:81)
	at io.cucumber.datatable.DataTable.convert(DataTable.java:360)
	at io.cucumber.core.stepexpression.StepExpressionFactory.lambda$createExpression$0(StepExpressionFactory.java:66)
	at io.cucumber.core.stepexpression.DataTableArgument.getValue(DataTableArgument.java:19)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:47)
	... 33 more
`

**Comment by networkinss** [comment]
Fixed with version 1.6.0
